### ISSUE TITLE
hello mas raka

### ISSUE THREAD

**Issue by vianziro** [rakaadinugroho/Codeigniter-JWT-User-Authentication#1]
oh iya mas numpang tanya. ini dari core punya mas akhwan.
beritin ini cuma apinya aja ya ...lalu untuk intergrasi dengan aplikasi dengan punya mas akhwan disendirikan atau lagsung jadikan satu saja..

dan ini satu database dengan database mas akwan?

**Comment by rakaadinugroho** [comment]
iya, itu pengembangan dari core nya mas akhwan,.
untuk administrator data bisa pakai punya mas akhwan. yang di saya adalah API nya, tapi untuk database ada penambahan sesuai yang saya tuliskan di README

**Comment by vianziro** [comment]
saya edit webservicenya muncul error di line 33 config.php kenpa ya ?

trus di database.php 'dsn ' perlu diisi ndak?

**Comment by rakaadinugroho** [comment]
untuk dsn tidak perlu diisi. sebelumnya, anda melakukan setup di mana ? :) local ata server langsung

**Comment by vianziro** [comment]
saya pakai dilocal, tetap tidak bisa running aplikasi

**Comment by vianziro** [comment]
tidak ada error tapi not running di avd

**Comment by rakaadinugroho** [comment]
coba di buat online terlebih dahulu / pish ke server, nanti saya cek untuk endpointnya.
