### ISSUE TITLE
SQL File error

### ISSUE THREAD

**Issue by ariqbanihardi** [rakaadinugroho/Codeigniter-JWT-User-Authentication#2]
Mas Raka, boleh dishare SQL file nya. yang dari [https://github.com/akhwan90/cat](url) banyak table yang gak ada kalo pake CI ini. sama kalo mau dapetin dokumentasi API-nya dimana ya? terimakasih

**Comment by rakaadinugroho** [comment]
Ada mas, file SQL nya sudah di repo

Pada tanggal Sen, 10 Sep 2018 19.47, ariqbanihardi <notifications@github.com>
menulis:

**Comment by ariqbanihardi** [comment]
dimana mas? kok aku gak nemu file sql nya

**Comment by rakaadinugroho** [comment]
ini file databasenya https://github.com/akhwan90/cat/blob/cat_dua/db_cat_dua.sql . nanti tambahan 1 table ada di Repo saya
