### ISSUE TITLE
thumnail

### ISSUE THREAD

**Issue by alitputri** [rakaadinugroho/Codeigniter-JWT-User-Authentication#3]
bang raka saya sudah menambahkan tabel thumnail pada database m_mapel
tapi di android sudah login tiba" aplikasi keluar sendiri dan gak bisa di pakai
solusinya bang raka

**Comment by rakaadinugroho** [comment]
pada saat nambahin kolomnya, dibikin autofill aja pakai default text aja misalnya URL icon gambar
